/*globals define*/
/*jshint node:true, browser:true*/

/**
 * Generated by PluginGenerator 1.7.0 from webgme on Wed Oct 19 2016 21:34:43 GMT-0500 (Central Daylight Time).
 * A plugin that inherits from the PluginBase. To see source code documentation about available
 * properties and methods visit %host%/docs/source/PluginBase.html.
 */

define([
    'plugin/PluginConfig',
    'text!./metadata.json',
    'plugin/PluginBase',
    'q'
], function (
    PluginConfig,
    pluginMetadata,
    PluginBase,
    Q) {
    'use strict';

    pluginMetadata = JSON.parse(pluginMetadata);

    /**
     * Initializes a new instance of MiniProject2.
     * @class
     * @augments {PluginBase}
     * @classdesc This class represents the plugin MiniProject2.
     * @constructor
     */
    var MiniProject2 = function () {
        // Call base class' constructor.
        PluginBase.call(this);
        this.pluginMetadata = pluginMetadata;
    };

    /**
     * Metadata associated with the plugin. Contains id, name, version, description, icon, configStructue etc.
     * This is also available at the instance at this.pluginMetadata.
     * @type {object}
     */
    MiniProject2.metadata = pluginMetadata;

    // Prototypical inheritance from PluginBase.
    MiniProject2.prototype = Object.create(PluginBase.prototype);
    MiniProject2.prototype.constructor = MiniProject2;

    /**
     * Main function for the plugin to execute. This will perform the execution.
     * Notes:
     * - Always log with the provided logger.[error,warning,info,debug].
     * - Do NOT put any user interaction logic UI, etc. inside this method.
     * - callback always has to be called even if error happened.
     *
     * @param {function(string, plugin.PluginResult)} callback - the result callback
     */
    MiniProject2.prototype.main = function (callback) {
        // Use self to access core, project, result, logger etc from PluginBase.
        // These are all instantiated at this point.
        var self = this,
            nodeObject,
            artifact;

        MiniProject2.prototype.loadNodeMap = function (node) {
            var self = this;
            return self.core.loadSubTree(node)
                .then(function (nodeArr) {
                    var nodes = {},
                        i;
                    for (i = 0; i < nodeArr.length; i += 1) {
                        nodes[self.core.getPath(nodeArr[i])] = nodeArr[i];
                    }

                    return nodes;
                });
        };
        self.metaNodeInfo = [];



        self.loadNodeMap(self.rootNode);
        var self = this,
            nodeObject,
            jsonModel,
            obj=[],
            artifact;


        nodeObject = self.activeNode;

        self.loadNodeMap(nodeObject)
            .then(function (nodes) {
                self._nodes = nodes;
                obj.push(self.buildTreeInfo(self.rootNode,nodes,''))
                self.buildMetaInfo(self.rootNode,nodes,'');
                //self.logger.info(JSON.stringify(self.metaNodeInfo, null, 4));
                //self.logger.info(JSON.stringify(obj, null, 4));

                return self.generateArtifact(self.metaNodeInfo, obj);
            })
            .then(function (artifactHash) {
                self.result.addArtifact(artifactHash);
                self.result.setSuccess(true);
                callback(null, self.result);
            })
            .catch(function (err) {
                // Result success is false at invocation.
                self.logger.error(err.stack);
                callback(err, self.result);
            });

    };
    MiniProject2.prototype.buildMetaInfo = function (root, nodes, indent) {
        var self = this,
            childrenPaths,
            childNode,
            i,
            isMetaNode,
            metaNode,
            metaPath,
            myPath,
            name,
            isConnection = false,
            base,
            src,
            dst,
            base,
            connectStr = '';
        indent = indent || '';
        childrenPaths = self.core.getChildrenPaths(root);

        // detecting if it is a meta node
        name = self.core.getAttribute(root, 'name');
        metaNode = self.getMetaType(root);
        metaPath = self.core.getPath(metaNode);
        myPath = self.core.getPath(root);


        isMetaNode = (metaPath === myPath);
        //self.logger.info(name,metaPath,myPath, "isMeta", (metaPath === myPath));

        // checking if it is a connection node
        src = self.core.getPointerPath(root, 'src');
        dst = self.core.getPointerPath(root, 'dst');
        base = self.core.getPointerPath(root, 'base');
        if (base) {
            base = nodes[base];
            base = self.core.getAttribute(base, "name");
        }
        else {
            base = 'null'
        }
        if (src && dst) {
            isConnection = true;
            src = nodes[src];
            dst = nodes[dst];
            src = self.core.getAttribute(src, "name");
            dst = self.core.getAttribute(dst, "name");
            connectStr = src + " --> " + dst;
        }
        self.logger.info(indent, "isMeta", isMetaNode, "isConnection", isConnection, self.core.getAttribute(root, 'name'), 'has', childrenPaths.length, "children.", connectStr);
        if (isMetaNode) {
            if (isConnection)
                self.metaNodeInfo.push({
                    name: name,
                    path: myPath,
                    numberOfChildren: childrenPaths.length,
                    connection: connectStr,
                    base: base
                });
            else
                self.metaNodeInfo.push({
                    name: name,
                    path: myPath,
                    numberOfChildren: childrenPaths.length,
                    base: base
                });
            }

        for (i = 0; i < childrenPaths.length; i++) {
            childNode = nodes[childrenPaths[i]];
            self.buildMetaInfo(childNode, nodes, '');
        }
    };

    MiniProject2.prototype.buildTreeInfo = function (root, nodes, indent) {
        var self = this,
            childrenPaths,
            childNode,
            i,
            isMetaNode,
            metaNode,
            metaPath,
            myPath,
            name,
            isConnection = false,
            src,
            dst,
            tree = {},
            dict = [],
            connectStr = '';
        indent = indent || '';
        childrenPaths = self.core.getChildrenPaths(root);


        // detecting if it is a meta node
        name = self.core.getAttribute(root, 'name');
        metaNode = self.getMetaType(root);
        metaPath = self.core.getPath(metaNode);
        myPath = self.core.getPath(root);


        isMetaNode = (metaPath === myPath);
        //self.logger.info(name,metaPath,myPath, "isMeta", (metaPath === myPath));

        // checking if it is a connection node
        src = self.core.getPointerPath(root, 'src');
        dst = self.core.getPointerPath(root, 'dst');
        var metaNode = self.core.getBaseType(root),
            nodeName = self.core.getAttribute(root, 'name'),
            // Library-roots do not have a meta-type either.
            metaName = metaNode ? self.core.getAttribute(metaNode, 'name') : ':LibraryRoot:';
        if (src && dst) {
            isConnection = true;
            src = nodes[src];
            dst = nodes[dst];
            src = self.core.getAttribute(src, "name");
            dst = self.core.getAttribute(dst, "name");
            connectStr = src + " --> " + dst;
        }
        var children= {};
        for (i = 0; i < childrenPaths.length; i++) {
            childNode = nodes[childrenPaths[i]];

            var Path = self.core.getRelid(childNode);



            children[Path] =  self.buildTreeInfo(childNode, nodes, indent + '  ');

        }
        if (isConnection) {
            tree = ({
                name: name,
                isMeta: isMetaNode,
                metaType: metaName,
                src: src,
                dst: dst,
                connection: connectStr,
                children: children
            });
        }
        else {
            tree = ({
                name: name, isMeta: isMetaNode, metaType: metaName, children: children
            });
        }
        return tree


    };
    MiniProject2.prototype.generateArtifact = function (jsonModel, obj) {
        var self = this,
            deferred = Q.defer(),
            language,
            artifact,
            filesToAdd = {},
            codeFileName,
            batchFileName;

        artifact = self.blobClient.createArtifact('project-data');
        filesToAdd['meta.json'] = JSON.stringify(jsonModel, null, 4);
        filesToAdd['tree.json'] = JSON.stringify(obj, null, 4);



        artifact.addFiles(filesToAdd, function (err) {
            if (err) {
                deferred.reject(new Error(err));
                return;
            }
            self.blobClient.saveAllArtifacts(function (err, hashes) {
                if (err) {
                    deferred.reject(new Error(err));
                    return;
                }

                deferred.resolve(hashes[0]);
            });
        });
            return deferred.promise;
        };


    return MiniProject2;
});
